name : to create a Instance and VPC setup in AWS environment 
on:
  workflow_dispatch
jobs:
  terraform:
    name: Terraform Deploy
    runs-on: Ubumtu-latest 

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform plan 
      - run: terraform apply -auto-approve